baseURL = "https://widgetfactory.co"
languageCode = "en-us"
title = "⚓ Widget Factory:  Brian Danowski's Blog about Tech, Programming, Devops, and Stuff"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-101993562-1"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
[Params]
    tagline = "Tech, Programming, DevOps, and Stuff"
    author = "Brian Danowski"
    description = "Full-stack polyglot programmer"
    logoBig = "/images/widget-factory-logo.png"
    logoSmall = "/images/widget-factory-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/widget-factory-logo.png"
    twitter = "briandanowski"
    linkedin = "bdanowski"
    github = "mailtruck"
    email = "briandanowski@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[permalinks]
    gallery = "/" # Redirect gallery index to home page

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
#[[menu.main]]
#    name = "Work"
#    url  = "/#work"
#    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
